// Code generated by Wire Inject.DO NOT EDIT
package inject

import (
	"utils/wire_inject/example/inner"

	"github.com/google/wire"
)

var HelperSet = wire.NewSet(
	wire.Struct(new(inner.ChrisWu), "*"),
	wire.Bind(new(inner.Rapper), new(*inner.ChrisWu)),

	inner.InitZXY,
	wire.Bind(new(inner.Singer), new(*inner.ZXY)),

	wire.Struct(new(inner.ZhaoSi), "*"),
	wire.Bind(new(inner.Dancer), new(*inner.ZhaoSi)),

	wire.Struct(new(inner.Kobe), "*"),
	wire.Bind(new(inner.Player), new(*inner.Kobe)),
)
