package wire_inject

const injectSetNameTemplate = `// Code generated by Wire Inject.DO NOT EDIT
package %s

import (
	"github.com/google/wire"
)

var %s = wire.NewSet(
	%s,
)
`

const injectSetsTemplate = ``
